// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_sku_service.proto

package io.reactivesw.catalog.grpc;

public final class CatalogSkuService {
  private CatalogSkuService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\031catalog_sku_service.proto\022$io.reactive" +
      "sw.catalog.infrastructure\032\033google/protob" +
      "uf/empty.proto\032\036google/protobuf/wrappers" +
      ".proto\032\031catalog_sku_message.proto2\313\001\n\nSk" +
      "uService\022M\n\021querySkuInventory\022\033.google.p" +
      "rotobuf.Int64Value\032\033.google.protobuf.Int" +
      "32Value\022n\n\031querySkuSimpleInformation\022\033.g" +
      "oogle.protobuf.Int64Value\0324.io.reactives" +
      "w.catalog.infrastructure.SkuInformationB" +
      "\036\n\032io.reactivesw.catalog.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    io.reactivesw.catalog.grpc.CatalogSkuMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
