// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: catalog_service.proto

package io.reactivesw.catalog.grpc;

public final class CatalogService {
  private CatalogService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025catalog_service.proto\022$io.reactivesw.c" +
      "atalog.infrastructure\032\033google/protobuf/e" +
      "mpty.proto\032\036google/protobuf/wrappers.pro" +
      "to\032\025catalog_message.proto2\322\001\n\017CategorySe" +
      "rvice\022[\n\rgetCategories\022\026.google.protobuf" +
      ".Empty\0322.io.reactivesw.catalog.infrastru" +
      "cture.CategoryList\022b\n\017getCategoryById\022\033." +
      "google.protobuf.Int64Value\0322.io.reactive" +
      "sw.catalog.infrastructure.GrpcCategory2\342" +
      "\001\n\016ProductService\022l\n\025getProductsByCatego",
      "ry\022\033.google.protobuf.Int64Value\0326.io.rea" +
      "ctivesw.catalog.infrastructure.ProductBr" +
      "iefList\022b\n\020getProductDetial\022\033.google.pro" +
      "tobuf.Int64Value\0321.io.reactivesw.catalog" +
      ".infrastructure.GrpcProductB\036\n\032io.reacti" +
      "vesw.catalog.grpcP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.EmptyProto.getDescriptor(),
          com.google.protobuf.WrappersProto.getDescriptor(),
          io.reactivesw.catalog.grpc.CatalogMessage.getDescriptor(),
        }, assigner);
    com.google.protobuf.EmptyProto.getDescriptor();
    com.google.protobuf.WrappersProto.getDescriptor();
    io.reactivesw.catalog.grpc.CatalogMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
